### ISSUE TITLE
Add predefined globals?

### ISSUE THREAD

**Issue by jacksonludwig** [josa42/coc-lua#45]
I would like to use this server for roblox lua programming, which is mostly lua but with some differences, namely a set of global variables. 

Is it possible to make the language server ignore a list of predefined variables?

**Comment by heapslip** [comment]
bumping this, also @ludwj61 you can use https://github.com/neovim/nvim-lsp#sumneko_lua meanwhile

**Comment by josa42** [comment]
Does adding the globals to [`. luacheckrc`](https://luacheck.readthedocs.io/en/stable/config.html) fix the issue?
