### ISSUE TITLE
Server fail to start

### ISSUE THREAD

**Issue by Gaulm** [josa42/coc-lua#47]
The server apparently can't start, I get this error: 

> `Error: No results matching query were found for Lua 5.4.
To check if it is available for other Lua versions, use --check-lua-versions.`
> `[coc.nvim] Server lua failed to start: Launching server "lua" using command /home/marco/.config/coc/extensions/coc-lua-data/tools/bin/lua-lsp failed.`

I tried to check the folder but my bin folder is empty, I don't have anything named lua-lsp inside of it.

**Comment by Gaulm** [comment]
Quick fix, since [lua-lsp](https://github.com/Alloyed/lua-lsp) supports lua versions up to 5.3 it is not possible to install it for the latest which is 5.4. First of all assert luarocks is installed then launch these 2 commands: 
`cd /home/USER/.config/coc/extensions/coc-lua-data/tools/`
`luarocks install --tree . --server=http://luarocks.org/dev lua-lsp --lua-version 5.3`
Lua 5.3 might be required to be installed, I don't know, it was already there on my system.
This might be a solution suitable for this plugin too, until lua-lsp provides the version for lua 5.4

**Comment by bratekarate** [comment]
Would be great if the lua version could be specified through `coc-settings.json`. Then in `/src/utils/tools.ts` this property could be used to add `--lua-version <VERSION>` to the install command.

Edit: created a PR with an added config property `version`.

**Comment by josa42** [comment]
Should be fixed by adding the lua version in `coc-settings.json` (#49)
