### ISSUE TITLE
Configuring lua-language-server and coc-lua to know about the neovim lua runtime?

### ISSUE THREAD

**Issue by lanza** [josa42/coc-lua#55]
Have you figured out how to point this to the neovim runtime so that

```
local api = vim.api  #Undefined global `vim`.
```

ends up working properly?

**Comment by lanza** [comment]
Figured it out two minutes later. For posterity:

```
  "Lua": {
    "workspace.library": {
      "/usr/share/nvim/runtime/lua": true,
      "/usr/share/nvim/runtime/lua/vim": true,
      "/usr/share/nvim/runtime/lua/vim/lsp": true,
    },
    "diagnostics": {
      "globals": ["vim"]
    }
  },
```

**Comment by elzii** [comment]
@lanza would you mind sharing your `coc-settings.json` in full? Having issues myself...

**Comment by Dkendal** [comment]
Just chipping in after trying to fix some lua lsp issues that v1.15.0 of lua-language-server appears to not work with neovim.

**Comment by s-taylor** [comment]
@lanza thankyou, that was a massive help!

**Comment by AlanJui** [comment]
> @lanza would you mind sharing your `coc-settings.json` in full? Having issues myself...

Install lua-language-server manually. (Ref URL: `https://github.com/sumneko/lua-language-server/wiki/Build-and-Run` )

```
{
  "languageserver": {
    "lua": {
      "command": "/home/alanjui/.local/share/lua-language-server/bin/Linux/lua-language-server",
      "args": [
        "-E",
        "/home/alanjui/.local/share/lua-language-server/bin/Linux/main.lua"
      ],
      "filetypes": ["lua"],
      "settings": {
        "Lua": {
          "workspace.library": {
            "/usr/share/nvim/runtime/lua": true,
            "/usr/share/nvim/runtime/lua/vim": true,
            "/usr/share/nvim/runtime/lua/vim/lsp": true
          },
          "diagnostics": {
            "globals": [ "vim" ]
          }  
        }
      }
    }
  }
}
```

**Comment by cstsunfu** [comment]
Is there a way not to install lua-language-server manually to figure out this issue?

**Comment by romgrk** [comment]
`coc-settings.json` with no manual installation:

```jsonc
{
  "Lua.workspace.library": {
    "/usr/local/share/nvim/runtime/lua": true,
    "/usr/local/share/nvim/runtime/lua/vim": true,
    "/usr/local/share/nvim/runtime/lua/vim/lsp": true
  },
  "Lua.diagnostics.globals": ["vim"],
}
```

**Comment by chaudry-786** [comment]
For anyone still struggling; 

I used https://github.com/xiyaowong/coc-sumneko-lua
```
CocInstall  coc-sumneko-lua
```
My coc-settings.json 
```
{
    "sumneko-lua.enableNvimLuaDev": true,
}
```
Works perfectly.

**Comment by nullromo** [comment]
The format of CoC config has changed slightly. `Lua.workspace.library` is an array. It should look like this now.

```json
"Lua.workspace.library": [
    "/usr/local/share/nvim/runtime/lua",
    "/usr/local/share/nvim/runtime/lua/vim",
    "/usr/local/share/nvim/runtime/lua/vim/lsp"
],
"Lua.diagnostics.globals": ["vim"]
```

If you installed Neovim using [bob](https://github.com/MordechaiHadad/bob), you might have to point to another location, like for example `"/home/my-user/.local/share/bob/v0.11.4/share/nvim/runtime/lua"`.
