### ISSUE TITLE
How can I disable workspace diagnostics

### ISSUE THREAD

**Issue by nemya9066** [josa42/coc-lua#57]
Hello whenever I edit a lua file in my home directory the workspace diagnostic feature is killing my cpu (my bad I have an old machine not a problem with performance) don't know what this feature does and don't care completion working fine please what option to disable it?
I tried setting "Lua.diagnostics.workspaceDelay" to -1 as the README said that a negative value would disable the feature but it didn't any help?

**Comment by nemya9066** [comment]
it seems that ignoring my . directory with "Lua.workspace.ignoreDir" does help still isn't there a simple option to only check for opened files?

**Comment by josa42** [comment]
You could disable diagnostics all together by setting `Lua.diagnostics.enable` to false.
Please, report issues with `lua-language-server` here: https://github.com/sumneko/lua-language-server

See also:
- https://github.com/sumneko/lua-language-server/issues/329
- https://github.com/sumneko/lua-language-server/issues/390
