### ISSUE TITLE
Keeps on trying to get access to contacts, reminders, photos

### ISSUE THREAD

**Issue by poetaman** [josa42/coc-lua#58]
When I start nvim from home directory, and open a lua file in another directory (in my case ~/Desktop/somefolder/file.lua), I keep on getting popup messages that some subprocess of my terminal is trying to access contacts, reminders, and photos. Is there a way to disable filesystem search? I have following settings, but it still doesn't stop:

```
{
    "Lua.telemetry.enable": false,
    "Lua.workspace.maxPreload": 0,
    "Lua.workspace.library": {},
    "Lua.diagnostics.enable": false
}
```

Is it possible to hardcode directory paths that should be ignored? While in home directory, a reverse option would work better: allow only certain sub-directories.

**Comment by poetaman** [comment]
Got around this by adding all the folders in my home directory to ``.gitignore`` file.

**Comment by oblitum** [comment]
This should really be reopened I think. With raw language server configuration one can set `"ignoredRootPaths": ["~"]`  to avoid the server from scanning the entire home folder. There's no option to do the same with the extension.

**Comment by oblitum** [comment]
Or [maybe it's a coc.nvim issue](https://github.com/sumneko/lua-language-server/issues/480#issuecomment-841754073).
