### ISSUE TITLE
Add formatter support

### ISSUE THREAD

**Issue by LordMZTE** [josa42/coc-lua#60]
Currently, coc-lua doesn't seem to be able to format the current buffer.
Running `:call CocCommand('format')` in a lua file prints an error message saying the language server doesn't support formatting.
Would it be possible to add such functionality to coc-lua?

**Comment by josa42** [comment]
Formatting would need to be implemented in the language server: https://github.com/sumneko/lua-language-server/issues/440

**Comment by Lilja** [comment]
It looks like this has been implemented by the language server now?

**Comment by zsmatrix62** [comment]
looking forward for this feature.
