### ISSUE TITLE
Using Dictionary as string

### ISSUE THREAD

**Issue by Xandaros** [josa42/coc-lua#64]
Triggering auto-complete after `foo(` results in one of two errors:
```
[coc.nvim]: UnhandledRejection: c.content.trim is not a function
TypeError: c.content.trim is not a function
    at /home/xandaros/dotfiles/config/nvim/bundle/coc.nvim/build/index.js:223:21299
    at Array.filter (<anonymous>)
    at qC.show (/home/xandaros/dotfiles/config/nvim/bundle/coc.nvim/build/index.js:223:21279)
    at b9.onPumChange (/home/xandaros/dotfiles/config/nvim/bundle/coc.nvim/build/index.js:223:31866)
```
```
Error detected while processing function coc#_complete:
line    3:
E731: using Dictionary as a String
```

The definition of `foo`:
```lua
---@param x number
---@param y fun()?
function foo(x, y)
end
```

The first parameter has to exist, and the second has to be an optional function. As far as I can tell, those are the conditions for this to fail.

**Comment by oblitum** [comment]
I can't reproduce this one:

![img-2021-06-17-142759](https://user-images.githubusercontent.com/1269815/122445786-42e10380-cf78-11eb-8fb9-d5863452cec2.png)

**Comment by Xandaros** [comment]
Hmm, now I can't reproduce it any more, either. There must have been something else contributing to it...

Well, the `?` to mark something as optional doesn't seem to work anyway and I replaced it with `| nil`, which works without issue.
